services:
  builder:
    build: .
    image: owrt-src-fw-builder:latest
    container_name: owrt-src-fw-builder
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./profiles:/builder/profiles:rw
      - ./source:/builder/source
      - ./dl:/builder/dl
      - ./.ccache:/builder/ccache
      - ./artifacts:/builder/artifacts:rw
      # - ./my-personal-scripts:/builder/uci-defaults-extra:ro
